from numpy import place
import locationtagger

sample_text = "ON 17 FEB 22, THE GENERAL SY SITUATION IN AOR AS AT THE TIME OF THIS REPORT IS RELATIVELY PEACEFUL. HUMAN AND VEHICULAR MOVEMENTS ARE ONGOING AS WELL AS RESUMPTION OF SCHOOLS, OFFICES AND COMMERCIAL ACTIVITIES THAT WERE HITHERTO GROUNDED ON 16 FEB 22 SEQUEL TO THE ILLEGAL SIT-AT-HOME ORDER WHICH RECORDED HUNDRED PERCENT COMPLIANCE. MEANWHILE, ON 16 FEB 22 AT ABOUT 1515HRS, HOODLUMS SUSPECTED TO BE OF IPOB/ESN ALONG UKWUINYI ROAD ENUGU-EZIKE IN IGBO-EZE NORTH LGA ATTACKED A COMMERCIAL BUS COMING FROM KOGI STATE THROUGH AJI AND BURNT ONE OF THE BUS'S TYRES, DESTROYED THE WINDSCREEN AND WINDOW GLASSES. HOWEVER, NO LIFE  WAS LOST BUT THE DRIVER AND PASSENGERS WERE INSTRUCTED TO RETURN BACK TO WHERE THEY WERE COMING FROM. SECURITY OPERATIVES ARE POSITIONED AT STRATEGIC POINTS WITH A VIEW TO COUNTERING ANY ATTACK FROM SUSPECTED IPOB/ESN ELEMENTS. THE SITUATION IS BEING MONITORED."

place_entity = locationtagger.find_locations(text = sample_text)

print(
    place_entity.countries, place_entity.regions, 
    place_entity.cities
)

print(
    place_entity.country_cities, place_entity.country_regions, 
    place_entity.region_cities, place_entity.other_regions,
    place_entity.other
)
